const Menu = [
  {
    id: 1,
    name: "Chicken Thali",
    image: "images/1.jpg",
    category: "lunch",
    price: 250,
    description: "lorem Ipsum jhbghevghvghev jbvgvewghvgh jhbjhbgh",
  },
  {
    id: 2,
    name: "Poori Ghugni",
    image: "images/2.jpg",
    category: "breakfast",
    price: 250,
    description: "lorem Ipsum jhbghevghvghev jbvgvewghvgh jhbjhbgh",
  },
  {
    id: 3,
    name: "Mutton Biriyani",
    image: "images/3.jpg",
    category: "dinner",
    price: 250,
    description: "lorem Ipsum jhbghevghvghev jbvgvewghvgh jhbjhbgh",
  },
  {
    id: 4,
    name: "Idli & Dhosha",
    image: "images/4.jpg",
    category: "breakfast",
    price: 250,
    description: "lorem Ipsum jhbghevghvghev jbvgvewghvgh jhbjhbgh",
  },
  {
    id: 5,
    name: "Pakoda",
    image: "images/5.jpg",
    category: "evening",
    price: 250,
    description: "lorem Ipsum jhbghevghvghev jbvgvewghvgh jhbjhbgh",
  },
  {
    id: 5,
    name: "Chicken Dum Biriyani",
    image: "images/5.jpg",
    category: "special",
    price: 250,
    description: "lorem Ipsum jhbghevghvghev jbvgvewghvgh jhbjhbgh",
  },
];
export default Menu;
